[phases.setup]
nixPkgs = ["python312", "ffmpeg"]  # Python 3.12 + FFmpeg

[phases.build]
cmd = "python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"

[start]
cmd = "python main.py"